# Form implementation generated from reading ui file 'Project_1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Grade Calculator")
        MainWindow.resize(300, 423)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(parent=self.centralwidget)
        self.title.setGeometry(QtCore.QRect(100, 0, 101, 16))
        self.title.setObjectName("title")
        self.student_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.student_label.setGeometry(QtCore.QRect(10, 60, 131, 16))
        self.student_label.setObjectName("student_label")
        self.students_output = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.students_output.setGeometry(QtCore.QRect(140, 60, 104, 21))
        self.students_output.setObjectName("students_output")
        self.scores_output = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.scores_output.setGeometry(QtCore.QRect(140, 100, 104, 21))
        self.scores_output.setObjectName("scores_output")
        self.score_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.score_label.setGeometry(QtCore.QRect(40, 100, 81, 16))
        self.score_label.setObjectName("score_label")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 140, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.output = QtWidgets.QLabel(parent=self.centralwidget)
        self.output.setGeometry(QtCore.QRect(9, 175, 281, 241))
        self.output.setText("")
        self.output.setObjectName("output")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 140, 113, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Grade Calculator"))
        self.student_label.setText(_translate("MainWindow", "Number of Students:"))
        self.score_label.setText(_translate("MainWindow", "Enter Scores:"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.pushButton_2.setText(_translate("MainWindow", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())

